name: If battery full and spare power turn on switch
if:
  - app: Growatt
    condition: is_battery_full
  - app: Growatt
    condition: is_input_above
    args:
      kw: 3000
  - app: OpenWeather
    condition: is_before_nighttime
    args:
      minutes: 120
  - app: OpenWeather
    condition: is_average_temperature_below_c
    args:
      celsius: 15
  - app: Meross
    condition: is_on
    args:
      device_uuid: '2109070303221290855748e1e9752928'
then:
  - app: Meross
    action: action_on
    args:
      device_uuid: '2109070303221290855748e1e9752928'
else:
  - app: Meross
    action: action_off
    args:
      device_uuid: '2109070303221290855748e1e9752928'
